import { ErrorCategory } from "@/shared/types";
import { BaseException } from "./BaseException";

/**
 * Base class for Persistence Errors (SDS Part 19 "PERSISTENCE ERRORS":
 * "Generated by repositories... Repositories shall never expose raw
 * Prisma exceptions.").
 *
 * Never thrown directly. Repositories (module MODULE 04 onward) define
 * concrete subclasses such as `EntityNotFoundError`,
 * `DuplicateEntityError`, `ConstraintViolationError`, and
 * `PersistenceFailureError`, translating raw Prisma errors into these
 * before they ever leave the persistence layer (SDS Part 19
 * "REPOSITORY ERROR CONTRACT").
 */
export abstract class RepositoryException extends BaseException {
  readonly category = ErrorCategory.Persistence;
}
