import type { SessionType } from "./enums";

/**
 * Domain-safe representation of a persisted Session.
 *
 * Mirrors the `Session` Prisma model (SDS Part 8). A session is created
 * when it starts; `completedAt` and `durationSeconds` remain null until
 * it is completed (supports the create()/complete() repository
 * lifecycle from SDS Part 9).
 */
export interface Session {
  readonly id: string;
  readonly sessionType: SessionType;
  readonly startedAt: Date;
  readonly completedAt: Date | null;
  readonly durationSeconds: number | null;
  readonly createdAt: Date;
}

/**
 * Domain-safe representation of a persisted SessionItem — the bridge
 * entity connecting a Session to the Pages studied within it
 * (SDS Part 8 "SESSIONITEM MODEL").
 */
export interface SessionItem {
  readonly id: string;
  readonly sessionId: string;
  readonly pageId: string;
  readonly order: number;
}

/**
 * A session that is currently in progress, together with the pages
 * already completed within it.
 *
 * Built entirely from persisted rows, so it stays correct across a
 * process restart. This is what lets a client reconcile its own idea of
 * "a session is in progress" against the server rather than trusting
 * local storage (SDS Part 12 "INTERRUPTED SESSIONS").
 */
export interface ActiveSessionProgress {
  readonly session: Session;
  readonly completedPageIds: readonly string[];
}

/**
 * Summary generated by the Learning Engine when a session completes
 * (SDS Part 12 "SESSION SUMMARY"). Deliberately excludes any computed
 * analytics — those remain the responsibility of the Analytics Engine.
 */
export interface SessionSummary {
  readonly sessionId: string;
  readonly sessionType: SessionType;
  readonly pagesCompleted: number;
  readonly totalRecallEvents: number;
  readonly durationSeconds: number;
  readonly completedAt: Date;
}
